title: "David Rihtaršič"
# pmarsceill/just-the-docs
# thema lepa, enostavna, simple, lahko urejaš nivo dokumenta, -nima postov
remote_theme: pmarsceill/just-the-docs
#color_scheme: "dark"
search_enabled: true
logo: "https://avatars3.githubusercontent.com/u/26739491?s=460&v=4"
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
  "Pa še en link":
    - "//github.com/pmarsceill/just-the-docs"
footer_content: "Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"


# tema od gihtuba
# ne znam narediti navigation
#theme: jekyll-theme-minimal

# thema minimal-mistakes
#remote_theme             : "mmistakes/minimal-mistakes"
#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#remote_theme: jekyll/jekyll
