title: "David Rihtaršič"
# tema od gihtuba
theme: jekyll-theme-minimal

#remote_theme: jekyll/jekyll

# thema lepa simple
#lahko urejaš nivo dokumenta
#nima postov
#remote_theme: pmarsceill/just-the-docs
#color_scheme: "dark"
#search_enabled: true
