title: "David Rihtaršič"
#remote_theme: jekyll/jekyll
#remote_theme: pmarsceill/just-the-docs
remote_theme: codeasashu/hcz-jekyll-blog
#color_scheme: "dark"
search_enabled: true

social:
  - service: github
    username: sobolevn
    link: https://github.com/sobolevn
  - service: twitter
    username: sobolevn
    link: https://twitter.com/sobolevn
